### ISSUE TITLE
Sort out the 'use' statements

### ISSUE THREAD

**Issue by caprenter** [Blushtones/testing#1]
I'm a bit confused about what needs to be in behat.yaml and what needs to be in FeatureContext.php.

@Plebster I think you said you knew what was going on and could fix!

**Comment by Plebster** [comment]
If we explicitly need the use statement(ie MinkConext) in the FeatureContext.php file then it should not be in the behat.yml file, I think that's how my head works with it...

**Comment by Plebster** [comment]
I can't close this issue :S

**Comment by caprenter** [comment]
Some permissions thing on setting up the repo and the organisation. You should be good now...
