### ISSUE TITLE
Create a standalone testing docker set up

### ISSUE THREAD

**Issue by caprenter** [Blushtones/testing#16]
Is there a way to set up a Drupal/Behat testing thing, as a standalone that we somehow include our tests in.

https://behat-drupal-extension.readthedocs.io/en/v4.0.1/index.html
https://behat-drupal-extension.readthedocs.io/en/v4.0.1/localinstall.html

**Comment by Plebster** [comment]
yes, no, probably... lets look at this when we have a suite of tests in place

**Comment by Plebster** [comment]
@caprenter I have a standalone solution that works, is this the best repository for it? it will require it's own docker compose, which is written... 

just a little bit of playing is required with the host files...

**Comment by caprenter** [comment]
Great. I'm not sure about which repo.

If you can clone this repo, run the docker compose and have your tests ready to run, then that would be good. (I'm thinking you just specify the URL to test?)

If it's more docker compose along side our existing worrk on that, then maybe in the other repository.

Again, I like the idea that I could just grab this repo, set everything up and test a live site, or a new site, independent from any other work. But that might not make sense as in practice it would always be part of a bigger project.
