### ISSUE TITLE
use region_map in custom code within featurecontext.php

### ISSUE THREAD

**Issue by Plebster** [Blushtones/testing#22]
I'm playing with some custom code to count news items videos etc... I can't see how to reference the region_map vars declared in the behat.yml within featurecontext.php... I don't seem to need them but they might useful in the future

**Comment by caprenter** [comment]
I think...

The function `getRegion` is in `/vendor/drupal/drupal-extension/src/Drupal/DrupalExtension/Context/MarkupContext`
It maybe just needs to be included (see https://www.drupal.org/project/drupalextension/issues/2416643 )

**Comment by caprenter** [comment]
This also looks like what you need: https://git.drupalcode.org/project/panopoly/blob/7.x-1.x/modules/panopoly/panopoly_test/behat/steps/panopoly_test.behat.inc#L927
That file also has lots of other useful functions we might want to use.

**Comment by caprenter** [comment]
I'm going to close this as it's not something we need now, or in order to proceed.

**Comment by Plebster** [comment]
hmm, not sure on that, might need to reopen this at some point to help with #5
