### ISSUE TITLE
Using Drush or Drupal API driver

### ISSUE THREAD

**Issue by caprenter** [Blushtones/testing#47]
Looking at the test you have done for a logged in user, these seem to be done with our own Feature Context definitions.
There are built in contexts that use the Drupal api (good for local test only) and Drush api -can also be used on remote sites - but I can't quite get my head round them.

Specifically, druapl api needs a 'path to a drupal installation' - I think because I am outside the container I can't specify it correctly (maybe?)
(If I try within the drupal container, I'm coming up against the Druapl/MinkExtension vs Behat\MinkExtension  (same as #16 ?) Which I think is solved by using Behat version 4 instead of 3?

maybe we can chat about how you've been getting on with these tests.

**Comment by Plebster** [comment]
our test environment isn't 'local' to our drupal installation as was requested in #16 

I think if you want these commands to work you will have to exec bash on to the drupal container and run Behat commands locally there.

I seem to remember this was vaguely mentioned in the trade offs between having a stand alone testing container and running the tests from within the drupal container

**Comment by Plebster** [comment]
I had to change the testing to the behat/minkextension in the standalone development as was recommended by the behat debug dialog 'big red square' but can't remember why... did the change, it fixed it and I moved on :/

**Comment by Plebster** [comment]
Sorry got bogged down by the technical bit there....

Missed the important question....

Why?

#15 and #45 work with featurecontext do we need to pursue another way to do the same thing?

**Comment by caprenter** [comment]
Thanks.

I think the behat/drupal thing is to do with versions of the Drupal Extension module (i.e. use 4 not 3) from what I googled, so that's all good.

The why is because Drupal Extension introduces a whole suite of tests, contexts, definitions that are drupal specific, so we don't need to roll our own.
Also the 'testuser' scenarios are failing for me because I have not yet created the user in the database - I suspect you did that somewhere that I didn't. On the LAMRT site a user with role 'team_member' can create an incident, but an authenticated user cannot (you would not be expected to know that!) but there are step definitions that use the Druapl API to deal with that already.
"Given I am logged in as a user with the :role role(s)"

I think I was coming to the understanding that 'it's not local' because of the containers - but the Drush API can get around that - it can test remote - but then I was wondering about the containers creating a local network, does than mean we are 'local' (just not local enough?)

To be honest - at this stage, I'm not too bothered about logged in user testing, it's a nice to have, and would be good to understand,but I can live without it as well.

Lets discuss in real life sometime - I'm around all day today

**Comment by Plebster** [comment]
#15 mentions creating users, this was for a security feature

**Comment by Plebster** [comment]
covered in 'local' testing
