### ISSUE TITLE
Test: Incident Reports

### ISSUE THREAD

**Issue by caprenter** [Blushtones/testing#6]
On /incidents

- [x] Should say Incident Reports 2021
- [x] Can see a bunch of incidents and has correct title
- [ ] Can select a year from 1970 to present
- [x] Selecting a year takes you to /incidents/<year> and you can see incidents

- [x] Should be 3 tabs: 

Incidents(active tab)
Map
Advanced Search

- [x] On Map tab there should be a map.
- [ ] Selector is from 2010 on wards
- [x] Click on a marker, should have text in?

Advance Search Tab

- [ ] Has Location, Type and Date selectors.

**Comment by Plebster** [comment]
I think might need selenium, not sure will look in the morning

**Comment by caprenter** [comment]
A couple of minor things not done, but that's ok
